# EMATM0048: SDPA 
## Teaching Session 8A: Numpy
`Original - Zahraa Abdallah `
`Nov 2020. `
`Modified - Qiang Liu Nov 2023`

NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

In [2]:
import numpy as np
import time
start_time= time.time()
my_arr = np.arange(10000000)
print("time for Numpy", time.time()-start_time)
start_time= time.time()
my_list = list(range(10000000))
print("time for Lists", time.time()-start_time)

time for Numpy 0.007561683654785156
time for Lists 0.1369619369506836


## Numpy's basic data structure: the ndarray

ndarray is used for storage of homogeneous data
i.e., all elements the same type
Every array must have a shape and a dtype
Supports convenient slicing, indexing and efficient vectorized computation

In [2]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 =  np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

`ndarray:`
- Arrays can have any number of dimensions, including zero (a scalar).
- Arrays are typed: np.uint8, np.int64, np.float32, np.float64
- Arrays are dense. Each element of the array exists and has the same type.


## Creating an array

- Using lists or tuples
- homogeneous data: zeros, ones
- diagonal elements: diag, eye
- numerical ranges: arange, linspace, logspace
- random numbers: rand, randint
- Reading from files


In [4]:
#List of lists
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]  #list of lists
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
#homogeneous data: zeros, ones
array= np.zeros((2,3))
print (array)
array = np.ones((2,3))
print (array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#diagonal elements: diag, eye
array = np.eye(3) 
print (array)
# a diagonal matrix
array= np.diag([1,2,3])
print (array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
#numerical ranges: arange, linspace, logspace
array = np.arange(0, 10, 2) # arange is an array-valued version of the built-in Python range function
print (array)

[0 2 4 6 8]


In [8]:
#random numbers: rand, randint
array = np.random.randint(0, 10, (3,3))
print (array)

[[9 3 9]
 [3 1 0]
 [4 1 7]]


## Type, size and shape of an array

- All elements of an ndarray are of the same type.
- The `ndarray.dtype` property is an attribute that specifies the data type of each element.
- The `ndarray.shape` property is a tuple that indicates the size of each dimension.
- The `ndarray.size` proprety indicates the number of elements in the array



In [9]:
arr = np.random.randint(0,10,(2,3))
print(arr)
print (arr.size, arr.shape, arr.dtype)

[[9 3 3]
 [9 1 7]]
6 (2, 3) int64


**Reshaping** an array: 

- Total number of elements cannot change.
- Use -1 to infer axis shape
- Row-major by default (MATLAB is column-major)

In [10]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(3,2)
print (a)
a = a.reshape(2,-1)
print(a)
a = a.ravel()
print(a)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


----------

## Accessing Arrays - Slicing and Indexing
### 1- Simple indexing

1d arrays: indexing and slicing as for lists
- first element has index 0
- negative indices count from the end
- slices: [start:stop:step]


In [11]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(3,2)

In [12]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a[2].shape

(2,)

In [14]:
a[2,:]

array([5, 6])

In [15]:
a[2:, :].shape

(1, 2)

### Slicing, careful it's a view!
A slice does not return a copy, which means that any modifications will be reflected in the source array. This is a design feature of NumPy to avoid memory problems.

In [16]:
arr = np.arange(10)
print(arr)          # [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [17]:
arr_slice = arr[5:8]
print(arr_slice)            # [5 6 7]

[5 6 7]


In [18]:
arr_slice[1] = 12345
print(arr)                      # [    0     1     2     3     4     5 12345     7     8     9]

[    0     1     2     3     4     5 12345     7     8     9]


In [19]:
arr_slice[:] = 64
print(arr)                      # [ 0  1  2  3  4 64 64 64  8  9]

[ 0  1  2  3  4 64 64 64  8  9]


### 2. Boolen indexing
Boolean indexing allows you to select data subsets of an array that satisfy a given condition.

In [20]:
#simple example
arr = np.array([10, 20])
idx = np.array([True, False])
arr[idx]

array([10])

In [21]:
arr

array([10, 20])

In [22]:
idx

array([ True, False])

In [23]:
arr = np.random.randn(10)
arr

array([-1.31839152, -1.09677327, -0.81409471, -0.87457341, -0.96067399,
       -0.85145902, -1.0238472 , -0.57581474, -1.20969964, -0.54208856])

In [24]:
arr<0.5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [25]:
#using a boolean index array inplace
arr[arr<0.5]

array([-1.31839152, -1.09677327, -0.81409471, -0.87457341, -0.96067399,
       -0.85145902, -1.0238472 , -0.57581474, -1.20969964, -0.54208856])

In [26]:
#Multiple conditins for masking
arr[(arr<0.5)&(arr>0)]

array([], dtype=float64)

In [27]:
#setting the value based on a boolean indexing array
arr[arr< 0] = 0
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3. Fancy indexing: 
list-of-locations indexing

In [3]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i,:] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [29]:
#To select out a subset of the rows in a particular order,
#you can simply pass a list or ndarray of integers specifying the desired order
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [30]:
# or using negative indexing
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passing multiple index arrays does something slightly different; it selects a 1D array of
elements corresponding to each tuple of indices:

In [31]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Take a moment to understand what just happened: the elements (1, 0), (5, 3), (7,
1), and (2, 2) were selected.

---------------

## Scalar-array operations
We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [33]:
A = np.array([[1,1],[3,3]])
A

array([[1, 1],
       [3, 3]])

In [34]:
A * 2

array([[2, 2],
       [6, 6]])

In [35]:
A + 2

array([[3, 3],
       [5, 5]])

### Element-wise array-array operations: Broadcasting
When we add, subtract, multiply and divide arrays with each other, the default behaviour is element-wise operations. Vectorized operations between arrays of different sizes and between arrays and scalars are subject to the rules of broadcasting. The idea is quite simple in many cases like with scalars:

In [36]:
print (A)
print (A * A) # element-wise multiplication

[[1 1]
 [3 3]]
[[1 1]
 [9 9]]


The case of arrays of different shapes is slightly more complicated.
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. 
see http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [37]:
#sizes are adjusted. that is called broadcasting and we look into this later
v1= np.arange(0,2)
print (A) #2x2
print (v1)# 1x2
A * v1

[[1 1]
 [3 3]]
[0 1]


array([[0, 1],
       [0, 3]])

### When broadcase can fail?
Only one array gets broadcasted. If both need to be adjusted, that will trigger an error

In [38]:
A= np.ones([7,8])
A

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
B= np.ones([9,3])
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
A+B

ValueError: operands could not be broadcast together with shapes (7,8) (9,3) 

----------

## Universal Functions: Fast Element-wise Array Functions
A universal function, or ufunc, is a function that performs elementwise operations on
data in ndarrays. You can think of them as fast vectorized wrappers for simple functions
that take one or more scalar values and produce one or more scalar results. For a full list of unfunc, check https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

In [41]:
#Many ufuncs are simple elementwise transformations, like sqrt or exp:
arr = np.random.randint(0, 10, (3,3))
print(arr)

[[9 7 8]
 [9 9 3]
 [1 8 0]]


In [42]:
np.sqrt(arr)

array([[3.        , 2.64575131, 2.82842712],
       [3.        , 3.        , 1.73205081],
       [1.        , 2.82842712, 0.        ]])

In [43]:
np.exp(arr) # exponential, Euler's constant

array([[8.10308393e+03, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 8.10308393e+03, 2.00855369e+01],
       [2.71828183e+00, 2.98095799e+03, 1.00000000e+00]])

A set of mathematical functions which compute statistics about an entire array or about
the data along an axis are accessible as array methods. Aggregations (often called
reductions) like sum, mean, and standard deviation std can either be used by calling the
array instance method or using the top level NumPy function:

In [44]:
arr.mean()
#or 
np.mean(arr)

6.0

In [45]:
arr.sum()

54

Functions like mean and sum take an optional axis argument which computes the statistic
over the given axis, resulting in an array with one fewer dimension:

In [46]:
arr.mean(axis=0)

array([6.33333333, 8.        , 3.66666667])