
# EMATM0048: Software Development Programming and Algorithms (SDPA)
# Exercise for Numpy


In [ ]:
## Ex 1: 
Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 
 
**Expected output:** 1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

In [ ]:
## Ex 2: 
Write a NumPy program to convert the values of Fahrenheit degrees into celsius degrees. 

**Expected Output:**
Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91]
Values in celsius degrees:
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [ ]:
## Ex 3:
Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

Original array:                                                        
[[ 0 10 20]
 [20 30 40]]                                                           
**Expected output:**
Values bigger than 10 = [20 20 30 40]                                  
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


In [ ]:
## Ex 4: 
Write a Python NumPy program to compute the weighted average for two arrays. 

The weighted arithmetic mean is similar to an ordinary arithmetic mean (the most common type of average), except that instead of each of the data points contributing equally to the final average, some data points contribute more than others. The notion of weighted mean plays a role in descriptive statistics and also occurs in a more general form in several other areas of mathematics.

Basic example
Given two school classes, one with 20 students, and one with 30 students, the grades in each class on a test were:
Morning class = 62, 67, 71, 74, 76, 77, 78, 79, 79, 80, 80, 81, 81, 82, 83, 84, 86, 89, 93, 98
Afternoon class = 81, 82, 83, 84, 85, 86, 87, 87, 88, 88, 89, 89, 89, 90, 90, 90, 90, 91, 91, 91, 92, 92, 93, 93, 94, 95, 96, 97, 98, 99

Weighted average is : 86 

In [ ]:
## Ex 5: 
Replace all odd numbers in the given array with -1. 

Sample input: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**Expected output:** [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
## Ex #6: 
Compute averages using a sliding window over an array?

Example: take the input [5, 2, 4, 6, 3, 1].A slidinhg winodow of size 2 is applied. The current sum of the pair, [5,2] is 7. Continue iterating through the entire array. One must slide the window up by 1 to reach the next iteration. The result is [3.5,3, 5, 4.5, 2]. Try with different window sizes. 

- More excercises at https://github.com/rougier/numpy-100
    

## Challenges: 

In [ ]:
 ## Ch #1: 
 Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?


In [ ]:
## Ch #2:
Create a 2D array subclass to create a symmetric matrix from random numbers such that Z[i,j] == Z[j,i]
An example symmetric matrix will look like:


[[ 1, 10,  7, 11,  3],

[10,  0,  8, 15,  2],


[ 7,  8,  9,  6,  6],

[11, 15,  6,  9, 12],
          
          
[ 3,  2,  6, 12,  2]]


# Exercise for Pandas: 

In this exercise, you will work with a data set in "mtcars.csv" that contains information on 31 cars. We will create a collection of scatterplots showing the relationship between horsepower (hp) and miles per gallon (mpg), displacement(disp) and quarter mile time (qsec).  Also, in each of these plots we will distinguish between automatic (am = 0) and manual (am=1) cars. Please follow the following steps: 

**Step 0:** create a gitHub repository for this exercise. In your local repository, copy this jupyter file. Make sure you commit and push changes to your online repository after each step. 

**Step 1:** Read the file into a data frame

**Step 2:** Dispaly statistics about differnt columns

**Step 3:** Create two dataframes from the origial one to represent manual and automatic cars

**Step 4:** Now Let's first create a 1x3 figure on which we will place the three plots. Give the figure a title of "Understanding the Effect of Horspower on other Features"

**Step 5:** On the first axis plot hp versus miles per gallon for manual cars only

**Step 6:** Add to the same axis a plot for automatic car, using a different color

**Step 7:** Repeat 5 and 6 for hp vs qsec

**Step 8:** Repeat 5 and 6 for hp vs disp

**Step 9:** Use descriptive labels, good markers, colors, and legends to enhance your graph

**Step 10:** Save figures to your computer 


Advanced: Add two horizontal lines to the first plot denoting the respective average mpg for automatic and manual cars respectively. 